### ISSUE TITLE
<i> and </i> are shown in results

### ISSUE THREAD

**Issue by vitorgalvao** [deanishe/alfred-glosbe#3]
This is translating English to Portuguese. Notice how the HTML italic tags are included in the results.

![image](https://user-images.githubusercontent.com/1699443/27518199-0033571a-59d2-11e7-9296-c4054e1240ec.png)

**Comment by deanishe** [comment]
Thanks for finding the bug.

I've fixed the tags thing, but this workflow is so old, there's quite a lot of other things I feel I should improve for Alfred 3.

In particular, Glosbe has gone from ~2000 languages to over 8000 (I had no idea there were that many!), so I need to move those data to sqlite to keep performance within acceptable limits.

I'm also going to rewrite the settings so you can directly copy the script you need for a new translation Script Filter.

I want to make this update good for another few years, as it's a huge pain updating a workflow that requires you to add your own elements (as they're deleted on update).

**Comment by vitorgalvao** [comment]
I’ve lost hope the Glosbe API will come back up, so closing.
